export const MARCAS_VEICULOS = [
  'Chevrolet', 'Fiat', 'Volkswagen', 'Ford', 'Honda', 'Toyota', 'Hyundai',
  'Renault', 'Nissan', 'Jeep', 'Peugeot', 'Citroën', 'Mitsubishi', 'Kia',
  'BMW', 'Mercedes-Benz', 'Audi', 'Volvo', 'Land Rover', 'Porsche',
  'Subaru', 'Suzuki', 'Caoa Chery', 'BYD', 'GWM/Haval', 'RAM', 'Dodge',
  'Mini', 'Yamaha', 'Shineray', 'Haojue',
] as const;

export const ESPECIALIDADES = [
  'Funilaria / Lanternagem',
  'Pintura Automotiva',
  'Mecânica Geral',
  'Mecânica Especializada (câmbio, motor)',
  'Elétrica Automotiva',
  'Vidros e Faróis',
  'Ar Condicionado',
  'Suspensão e Freios',
  'Polimento e Estética',
  'Tapeçaria / Estofamento',
  'Martelinho de Ouro',
  'Peças Novas',
  'Peças Recondicionadas',
  'Peças Importadas',
  'Reboque / Guincho',
  'Vistoria Cautelar',
] as const;

export const TIPOS_PECAS = [
  'Peças Novas',
  'Peças Usadas',
  'Peças Recondicionadas',
  'Peças Importadas',
  'Peças Genuínas / Originais',
  'Peças Paralelas / Alternativas',
] as const;

export const CATALOGO_PECAS = [
  'Para-choque Dianteiro',
  'Para-choque Traseiro',
  'Farol Dianteiro Direito',
  'Farol Dianteiro Esquerdo',
  'Lanterna Traseira Direita',
  'Lanterna Traseira Esquerda',
  'Capô',
  'Tampa Traseira / Porta-malas',
  'Paralama Dianteiro Direito',
  'Paralama Dianteiro Esquerdo',
  'Porta Dianteira Direita',
  'Porta Dianteira Esquerda',
  'Porta Traseira Direita',
  'Porta Traseira Esquerda',
  'Retrovisor Direito',
  'Retrovisor Esquerdo',
  'Para-brisa',
  'Vidro Traseiro',
  'Vidro Lateral',
  'Grade Dianteira',
  'Painel / Frontal',
  'Radiador',
  'Motor de Arranque',
  'Alternador',
  'Compressor Ar Condicionado',
  'Caixa de Câmbio',
  'Motor Completo',
  'Suspensão Dianteira',
  'Suspensão Traseira',
  'Roda / Aro',
] as const;
