project_id = "iyxdgmukrrdkffraptsx"

[functions.analise-consistencia-relatos]
verify_jwt = false

[functions.whatsapp-meta-webhook]
verify_jwt = false

[functions.despacho-reboque-responder]
verify_jwt = false

[functions.despacho-reboque-tracking]
verify_jwt = false

[functions.despacho-reboque-status]
verify_jwt = false

[functions.despacho-reboque-consultar]
verify_jwt = false

[functions.acompanhamento-reboque-consultar]
verify_jwt = false