INSERT INTO termos_aditivos (nome, descricao, conteudo_html, ativo, regras, ordem)
VALUES (
  'Termo Aditivo de Veículo Blindado',
  'Aditivo obrigatório para veículos blindados - exclui cobertura de blindagem, vidros blindados e componentes relacionados',
  '<h2 style="text-align: center; color: #1a1a6e; margin-bottom: 20pt;">TERMO ADITIVO DE VEÍCULO BLINDADO</h2>
<table class="fields-grid" style="margin-bottom: 15pt;"><tr><td colspan="4" class="section-title" style="background: #1a1a6e; color: white; text-align: center; font-weight: bold;">DADOS DA ASSOCIAÇÃO</td></tr><tr><td colspan="4"><span class="field-label">NOME:</span> <span class="field-value">{{empresa.nome}}</span><br/><span class="field-label">CNPJ:</span> <span class="field-value">{{empresa.cnpj}}</span><br/><span class="field-label">ENDEREÇO:</span> <span class="field-value">{{empresa.endereco}}</span></td></tr></table>
<table class="fields-grid" style="margin-bottom: 15pt;"><tr><td colspan="4" class="section-title" style="background: #1a1a6e; color: white; text-align: center; font-weight: bold;">DADOS DO VEÍCULO</td></tr><tr><td><span class="field-label">MARCA:</span> <span class="field-value">{{veiculo.marca}}</span></td><td><span class="field-label">MODELO:</span> <span class="field-value">{{veiculo.modelo}}</span></td><td><span class="field-label">PLACA:</span> <span class="field-value">{{veiculo.placa}}</span></td><td><span class="field-label">ANO:</span> <span class="field-value">{{veiculo.ano}}</span></td></tr><tr><td><span class="field-label">COR:</span> <span class="field-value">{{veiculo.cor}}</span></td><td><span class="field-label">RENAVAM:</span> <span class="field-value">{{veiculo.renavam}}</span></td><td colspan="2"><span class="field-label">CHASSI:</span> <span class="field-value">{{veiculo.chassi}}</span></td></tr></table>
<table class="fields-grid" style="margin-bottom: 15pt;"><tr><td colspan="4" class="section-title" style="background: #1a1a6e; color: white; text-align: center; font-weight: bold;">DADOS DO ASSOCIADO</td></tr><tr><td colspan="2"><span class="field-label">NOME:</span> <span class="field-value">{{associado.nome}}</span></td><td colspan="2"><span class="field-label">CPF/CNPJ:</span> <span class="field-value">{{associado.cpf}}</span></td></tr></table>
<div style="margin-top: 20pt;"><p style="text-align: justify; margin-bottom: 10pt;"><strong>Cláusula Primeira</strong> — A presente Aditivo objetiva assegurar que os veículos blindados ofereçam cobertura para a blindagem, suas partes componentes, vidros, forrações, peças blindadas e serviços correlatos.</p><p style="text-align: justify; margin-bottom: 10pt;"><strong>Cláusula Segunda</strong> — Em casos de colisão que ocasionem danos à blindagem, todas as despesas de reparo, reposição ou substituição de peças blindadas correrão exclusivamente por conta do proprietário/associado.</p><p style="text-align: justify; margin-bottom: 10pt;"><strong>Cláusula Terceira</strong> — Em casos de roubo, furto ou perda total do veículo blindado, a indenização ficará restrita ao valor de mercado do veículo, conforme Tabela FIPE vigente à época do evento, não sendo considerados custos adicionais da blindagem.</p><p style="text-align: justify; margin-bottom: 10pt;"><strong>Cláusula Quarta</strong> — A Associação disponibiliza aos associados o benefício de proteção para vidros e faróis. Todavia, fica expressamente esclarecido que tal benefício não se estende aos veículos blindados, sendo, portanto, de inteira responsabilidade do proprietário/associado quaisquer reparos, substituições ou reposições de vidros e faróis.</p><p style="text-align: justify; margin-bottom: 10pt;"><strong>Cláusula Quinta</strong> — Fica expressamente excluída da cobertura da Associação qualquer responsabilidade sobre a blindagem do veículo, incluindo manutenção, reparo, substituição de peças, vidros blindados ou quaisquer componentes relacionados ao sistema de blindagem, independentemente da causa do dano.</p><p style="text-align: justify; margin-bottom: 10pt;"><strong>Cláusula Sexta</strong> — A associação declara, neste ato, estar ciente de que a blindagem do veículo integra a cobertura e proteção veicular, tendo plena ciência de que eventuais custos decorrentes de reparos, substituições ou danos à blindagem serão de sua inteira responsabilidade.</p><p style="text-align: justify; margin-top: 15pt;">E por estarem de acordo, firmam o presente Termo Aditivo, em 2 vias de igual teor, para que produza seus efeitos legais.</p></div>',
  true,
  '[{"tipo": "veiculo_blindado", "ativo": true}]'::jsonb,
  3
);