-- Insert missing TERCEIROS_40 benefit
INSERT INTO public.beneficios_adicionais (codigo, nome, preco, categoria, descricao, ordem, ativo, variacao_por_cota)
VALUES ('TERCEIROS_40', 'Danos Terceiros 40mil', 0.00, 'Terceiros', 'Cobertura incluída no plano', 2, true, true)
ON CONFLICT DO NOTHING;

-- Insert configuration keys
INSERT INTO public.configuracoes (chave, valor, tipo, categoria) VALUES
  ('taxa_substituicao', '50', 'moeda', 'operacional'),
  ('taxa_fallback_carro', '0.025', 'percentual', 'operacional'),
  ('taxa_fallback_moto', '0.03', 'percentual', 'operacional'),
  ('decomposicao_cota', '0.60', 'percentual', 'rateio'),
  ('decomposicao_admin', '0.25', 'percentual', 'rateio'),
  ('decomposicao_rastreamento', '0.10', 'percentual', 'rateio'),
  ('decomposicao_assistencia', '0.05', 'percentual', 'rateio'),
  ('contato_cadastro', '21 98393-4083', 'texto', 'empresa'),
  ('contato_comercial', '21 99129-6732', 'texto', 'empresa'),
  ('glossario_consultor', '[{"termo":"ASSOCIADO","definicao":"Membro da associação. Não usamos o termo cliente."},{"termo":"EVENTOS","definicao":"Departamento responsável por indenizações, consertos e benefícios."},{"termo":"COTA DE PARTICIPAÇÃO","definicao":"Contribuição do associado no reparo. Calculada por categoria, plano e valor FIPE."},{"termo":"TABELA FIPE","definicao":"Preço médio de veículos no mercado nacional. Base para cálculos."},{"termo":"PROPOSTA DE FILIAÇÃO","definicao":"Documento principal com planos, benefícios e coberturas. 100% digital, assinatura em 1h."},{"termo":"CONTRIBUIÇÃO MENSAL","definicao":"Valor pago mensalmente à associação (não confundir com adesão)."},{"termo":"VISTORIA","definicao":"Avaliação do veículo no ato da filiação (31 fotos + vídeo)."},{"termo":"TROCA DE TITULARIDADE","definicao":"Transferência da proteção para novo proprietário (R$50 repasse + nova adesão)."},{"termo":"SUBSTITUIÇÃO DE PLACA","definicao":"Transferência da proteção para outro veículo do mesmo associado."},{"termo":"MIGRAÇÃO","definicao":"Associado vindo de outra proteção. Requer 4 últimos comprovantes. Sem carência."},{"termo":"DESÁGIO","definicao":"Desconto para associados que colocam adesivo publicitário (10% na mensalidade)."}]', 'json', 'operacional'),
  ('regras_importantes', '[{"titulo":"Ativação","icone":"⏰","itens":["Roubo/Furto: 00h do 1º dia útil após vistoria","Demais benefícios: 48h após vistoria/instalação"]},{"titulo":"Rastreador Obrigatório","icone":"📍","itens":["Carros >R$30.000","Motos >R$9.000","Plano Especial (todos)","Veículos diesel"]},{"titulo":"Instalação","icone":"🔧","itens":["RJ: 48h úteis","SP: 72h úteis"]},{"titulo":"Adesão","icone":"💰","itens":["Cálculo: 1% do valor FIPE","Mínimo Base: R$100","Mínimo Volante: R$150","Repasse Volante: R$50"]},{"titulo":"Inadimplência","icone":"⚠️","itens":["Benefícios suspensos no vencimento","5 dias para pagar sem revistoria","Após 5 dias: revistoria obrigatória (app gratuito)","Após 120 dias: nova adesão"]},{"titulo":"Autorização Necessária","icone":"📧","itens":["Veículos >R$120.000 (carros)","Veículos >R$30.000 (motos)","Email: cadastropraticcar@gmail.com"]}]', 'json', 'operacional'),
  ('cotas_taxas', '[{"categoria":"Passeio","percentual":"6%","minimo":"R$ 1.200","comDesagio":"8%","minimoDesagio":"R$ 2.000"},{"categoria":"APP","percentual":"8%","minimo":"R$ 3.000","comDesagio":"8%","minimoDesagio":"R$ 3.000"},{"categoria":"Deságio","percentual":"8%","minimo":"R$ 2.000"},{"categoria":"Motos","percentual":"10%","minimo":"R$ 1.500"},{"categoria":"Diesel","percentual":"6%","minimo":"R$ 2.500","comDesagio":"8%","minimoDesagio":"R$ 2.500"},{"categoria":"Especial Plus","percentual":"10%","minimo":"R$ 3.000"},{"categoria":"Lançamento","percentual":"10%","minimo":"R$ 3.000"},{"categoria":"Elétricos","percentual":"10%","minimo":"Sem mínimo"}]', 'json', 'operacional'),
  ('taxas_procedimentos', '[{"procedimento":"Adesão padrão","taxa":"R$ 350"},{"procedimento":"Substituição","taxa":"R$ 50"},{"procedimento":"Revistoria","taxa":"R$ 50"},{"procedimento":"Troca Titularidade","taxa":"R$ 50"},{"procedimento":"Multa Rastreador","taxa":"R$ 400"}]', 'json', 'operacional'),
  ('veiculos_aceitos', '{"CHEVROLET":["Agile","Astra","Celta","Cobalt","Corsa","Cruze","Meriva","Montana (até 2023)","Prisma","S10","Tracker (2009-2023)","Vectra","Vectra GT","Zafira","Onix","Spin","Classic","Joy"],"VW":["Fox","Gol","Kombi","Polo","Saveiro","Spacefox","Voyage","Up","Crossfox","Space Cross","Golf (>2008)","Virtus (até 2023)","Jetta (>2009)","Parati","T-Cross (até 2023)","Nivus (até 2023)"],"FIAT":["Doblo","Grand Siena","Idea","Linea","Palio","Punto","Siena","Strada","Uno","Palio Weekend","Mille","Mobi","Argo","Cronos (até 2023)","Fiorino","Ducato","Toro (até 2023)","Bravo","Pulse (até 2023)","Fastback (até 2023)"],"FORD":["Ecosport","Fiesta","Focus (>2009)","Ka (Novo)","Ranger (>2006)"],"RENAULT":["Clio","Kangoo","Logan","Sandero","Kwid","Duster (até 2023)","Master","Oroch (até 2019)","Captur (até 2019)"],"PEUGEOT":["207 (todos)","208","2008 (até 2014)"],"TOYOTA":["Etios","Corolla (2005-2023)","Yaris","Hilux (>2007)"],"HONDA":["City (até 2023)","Civic","Fit","HR-V","WR-V","CRV (>2010)"],"NISSAN":["Livina","March","Sentra","Tiida","Versa","Kicks (até 2023)","Frontier Flex (>2006)"],"HYUNDAI":["HB20","HR Diesel","Tucson Flex","Creta (até 2021)","IX35"],"JEEP":["Renegade Flex (até 2023)","Compass Flex (até 2023)"],"KIA":["Sportage Flex (>2007)","Cerato (>2009)","Bongo"],"CITROEN":["Aircross","C3 (até 2019)","C3 Picasso"],"MITSUBISHI":["Pajero TR4","Triton L200","Lancer","ASX","L200 Sport (>2005)"]}', 'json', 'operacional'),
  ('motos_aceitas', '{"HONDA":"Todos modelos nacionais (20 anos)","YAMAHA":"Todos modelos nacionais (20 anos)","SHINERAY":"Free 150 EFI (apenas Advanced)","BMW":"Apenas Advanced","HAOJUE":"Apenas Advanced","SUZUKI":"Apenas Advanced"}', 'json', 'operacional')
ON CONFLICT (chave) DO NOTHING;