UPDATE documento_templates
SET conteudo = REPLACE(
  REPLACE(
    conteudo,
    '<p><strong>O ASSOCIADO DECLARA QUE ESTÁ CIENTE QUE A PRATICCAR É UMA ASSOCIAÇÃO DE BENEFÍCIOS MÚTUOS, ONDE É REGIDA PELO ESTATUTO DE ACORDO COM AS NORMAS LEGAIS E QUE RECEBEU UMA CÓPIA DESTE MANUAL, LEU E TEM PLENO CONHECIMENTO DE TODAS AS NORMAS CONTIDAS NESTE REGULAMENTO E QUE ACEITA E CONCORDA COM TODAS AS CONDIÇÕES ESTABELECIDAS NESTE DOCUMENTO PARA ASSOCIAR-SE. DECLARA TAMBÉM QUE RECEBEU O REGULAMENTO DA ASSISTÊNCIA 24 HORAS E ESTÁ CIENTE DE TODO SEU CONTEÚDO.</strong></p>',
    ''
  ),
  'No caso de roubo ou furto, o associado deve comunicar imediatamente a PRATICCAR através do 0800 980 0001 o evento ocorrido; Caso o veículo protegido pela PRATICCAR seja conduzido por pessoa sem habilitação, o mesmo não estará coberto pelo programa de Benefícios Mútuos da PRATICCAR; O associado fica ciente que o rastreador instalado no veículo ficará sob sua responsabilidade em caráter de comodato e a não devolução do rastreador a PRATICCAR ocasionará ao associado o pagamento de uma multa estipulada em R$400,00; Os benefícios do PSM para veículo do associado cadastrado têm início às 00:00h no primeiro dia útil subsequente a data de aceitação da vistoria e da instalação do equipamento de rastreamento, quando obrigatório, sendo o início no ato que ocorrer por último.',
  'No caso de roubo, furto, incêndio, colisão e alagamento, o associado deve comunicar imediatamente a PRATICCAR através do 0800 980 0001 o evento ocorrido sob pena de negativa de cobertura; Caso o veículo protegido pela PRATICCAR infrinja as normas do Código de Trânsito Brasileiro (CTB), tais como: conduzir na contramão de direção; avançar o sinal semafórico ou o de parada obrigatória; dirigir sob efeito de álcool ou recusar-se a realizar o teste do etilômetro; exceder o limite de velocidade; manusear/utilizar o telefone celular ou pegar objetos no interior do veículo durante a condução; bem como cometer qualquer outra infração classificada como grave ou gravíssima, os benefícios previstos no Programa de Socorro Mútuo da PRATICCAR serão automaticamente negados; O associado fica ciente que o rastreador instalado no veículo ficará sob sua responsabilidade em caráter de comodato e a não devolução do rastreador à PRATICCAR ocasionará ao associado o pagamento de uma multa estipulada em R$400,00; Os benefícios de roubo, furto, colisão, alagamento e incêndio do PSM têm início no primeiro dia útil subsequente à data de aceitação da vistoria e da instalação do equipamento de rastreamento, quando obrigatório, sendo o início no ato que ocorrer por último. Os demais benefícios só estarão disponíveis após 48 horas (quarenta e oito horas) úteis após o prazo supracitado; O ASSOCIADO declara estar ciente de que a PRATICCAR é uma associação de benefícios mútuos, regida por seu Estatuto e em conformidade com as normas legais aplicáveis. Declara, ainda, que recebeu cópia do Regulamento Associativo e do Regulamento de Assistência 24 Horas, tendo lido, compreendido e possuindo pleno conhecimento de todas as normas neles contidas, as quais aceita e com as quais concorda integralmente, estando plenamente ciente de todo o seu conteúdo.'
)
WHERE id = 'eb09759f-cfbc-4ee8-8f1f-f1cc520e7279';