// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cllwtwywqfcjzpreqjep.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNsbHd0d3l3cWZjanpwcmVxamVwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjU0NDkzNTUsImV4cCI6MjA4MTAyNTM1NX0.fklMW0qJV4a77CvXKS00zte6x7LsesQB8U5A9YjdQnc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});