// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { initTelemetry, recordCall } from '@/lib/supabaseTelemetry';

const SUPABASE_URL = "https://iyxdgmukrrdkffraptsx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml5eGRnbXVrcnJka2ZmcmFwdHN4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjczODA2MDIsImV4cCI6MjA4Mjk1NjYwMn0.ky2mnyV-zad5peCNb8Ss16LaVlCQ8hWk6kwaQHStDnI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Fetch com timeout + telemetria leve (Fase 4):
// - timeout evita requisições travadas em backend lento
// - telemetria agrega contagem/duração por endpoint para a página /admin/telemetria
const fetchWithTimeout: typeof fetch = async (input, init) => {
  const url = typeof input === 'string' ? input : (input as Request).url;
  const method = (init?.method || (input instanceof Request ? input.method : 'GET') || 'GET').toUpperCase();
  const isAuthCall = url.includes('/auth/v1/');
  const timeoutMs = isAuthCall ? 15000 : 25000;

  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), timeoutMs);

  const externalSignal = init?.signal;
  if (externalSignal) {
    if (externalSignal.aborted) controller.abort();
    else externalSignal.addEventListener('abort', () => controller.abort(), { once: true });
  }

  const start = performance.now();
  let status = 0;
  let isTimeout = false;
  try {
    const res = await fetch(input, { ...init, signal: controller.signal });
    status = res.status;
    return res;
  } catch (err: any) {
    isTimeout = err?.name === 'AbortError';
    throw err;
  } finally {
    clearTimeout(timer);
    recordCall({
      url,
      method,
      status,
      durationMs: performance.now() - start,
      isTimeout,
    });
  }
};

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
  global: {
    fetch: fetchWithTimeout,
  },
}) as any;

// Inicializa o flush periódico (5 min) da telemetria
initTelemetry(supabase);
