// This file is automatically generated. Do not edit it directly.
import { createClient, SupabaseClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Criar storage isolado para evitar conflitos de sessão no preview do Lovable
const createIsolatedStorage = () => {
  const isLovablePreview = typeof window !== 'undefined' && 
    window.location.hostname.includes('lovable');
  
  // Se está no preview do Lovable, usar sessionStorage para ID único da aba
  const getSessionPrefix = (): string => {
    if (!isLovablePreview) return '';
    
    let sessionId = sessionStorage.getItem('lovable_tab_session_id');
    if (!sessionId) {
      sessionId = crypto.randomUUID().substring(0, 8);
      sessionStorage.setItem('lovable_tab_session_id', sessionId);
    }
    return `lovable_${sessionId}_`;
  };

  const prefix = getSessionPrefix();

  return {
    getItem: (key: string): string | null => {
      return localStorage.getItem(prefix + key);
    },
    setItem: (key: string, value: string): void => {
      localStorage.setItem(prefix + key, value);
    },
    removeItem: (key: string): void => {
      localStorage.removeItem(prefix + key);
    },
  };
};

// Singleton pattern para evitar múltiplas instâncias durante HMR
const getSupabaseClient = (): SupabaseClient<Database> => {
  const globalKey = '__SUPABASE_CLIENT__' as keyof typeof globalThis;
  
  if (typeof globalThis !== 'undefined' && (globalThis as Record<string, unknown>)[globalKey as string]) {
    return (globalThis as Record<string, unknown>)[globalKey as string] as SupabaseClient<Database>;
  }
  
  const client = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: createIsolatedStorage(),
      persistSession: true,
      autoRefreshToken: true,
    }
  });
  
  if (typeof globalThis !== 'undefined') {
    (globalThis as Record<string, unknown>)[globalKey as string] = client;
  }
  
  return client;
};

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = getSupabaseClient();